env="dev"

img_cache_path='/Users/developer/Desktop/cache/img'

[log]
biz_file='/Users/developer/Desktop/log/biz.log'
debug_file='/Users/developer/Desktop/log/debug.log'

[mysql]
host='localhost'
port=3306
username='root'
password='***'
database='freedom_project'

[oss]
prefix='dev/'
access_key='***'
access_secret='***'
endpoint='***'
img_bucket='***'
content_bucket='***'
