env="pord"

img_cache_path='/Users/developer/Desktop/cache/img'

[log]
biz_file='/home/freedomproject/log/article_spider/biz.log'
debug_file='/home/freedomproject/log/article_spider/debug.log'

[mysql]
host='***'
port=3306
username='***'
password='***'
database='freedom_project'

[oss]
prefix=''
access_key='***'
access_secret='***'
endpoint='***'
img_bucket='***'
content_bucket='***'

